# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-12 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=64)),
                ('m_duration', models.IntegerField(default=90)),
                ('m_leading_role', models.CharField(max_length=128)),
                ('m_director', models.CharField(max_length=64)),
                ('m_open_day', models.DateTimeField(default='1970-1-1 00:00:00')),
                ('m_mode', models.CharField(max_length=32)),
            ],
        ),
    ]
